FROM alpine

LABEL maintainer="Elvis"
ENV GOPATH=/go \
    PROJ_DIR=github.com/btcsuite/btcwallet

RUN apk add --no-cache git go musl-dev \
    && mkdir -p $GOPATH/src && cd $GOPATH/src \
    && go get -v $PROJ_DIR \
    && cd $PROJ_DIR \
    && go build \
    && go install . ./cmd/... \
    && apk del git go musl-dev \
    && rm -rf /apk /tmp/* /var/cache/apk/* $GOPATH/src/*

CMD ["/go/bin/btcwallet", "--help"]

